server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/client/**
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/account/**
      - id: credit-service
        uri: lb://credit-service
        predicates:
        - Path=/credit/**